from typing import List, Dict, Any
from app.integrations.llm.base import LLMProvider
from app.core.logging import logger

class MockLLMProvider(LLMProvider):
    async def generate_threat_narrative(self, analysis_data: Dict[str, Any], findings: List[Dict[str, Any]]) -> str:
        logger.info("Using MockLLMProvider to generate threat narrative.")
        
        narrative = f"[MOCK NARRATIVE]\n\n"
        narrative += f"The analyzed application '{analysis_data.get('app_name', 'Unknown')}' "
        narrative += f"(Package: {analysis_data.get('package_name', 'Unknown')}) has a deterministic risk score of {analysis_data.get('risk_score', 0)}/100.\n\n"
        
        # Risk Factors
        risk_factors = analysis_data.get('risk_factors', [])
        if risk_factors:
            narrative += "### Key Risk Factors:\n"
            for rf in risk_factors:
                narrative += f"- {rf['indicator']} (+{rf['weight']} pts)\n"
            narrative += "\n"
            
        # Components summary
        activities = analysis_data.get('activities', [])
        services = analysis_data.get('services', [])
        receivers = analysis_data.get('receivers', [])
        narrative += f"### Static Components:\n"
        narrative += f"- Activities: {len(activities)}\n"
        narrative += f"- Services: {len(services)}\n"
        narrative += f"- Broadcast Receivers: {len(receivers)}\n\n"
        
        if findings:
            narrative += "### Suspicious Indicators (MITRE ATT&CK Mapping):\n"
            for finding in findings:
                narrative += f"- {finding.get('title')}: {finding.get('description')} "
                if finding.get('mitre_technique_id'):
                    narrative += f"[{finding.get('mitre_technique_id')}] "
                narrative += f"(Severity: {finding.get('severity')})\n"
        else:
            narrative += "No highly suspicious indicators were found in static analysis.\n"
            
        narrative += "\n*This narrative was generated by the mock provider because no LLM API keys were available in the environment.*"
        return narrative
