"""add campaign intelligence fields

Revision ID: 4303ca248d3a
Revises: ca28bbe9dfd3
Create Date: 2026-09-12 11:25:03.102054

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4303ca248d3a'
down_revision = 'ca28bbe9dfd3'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('campaigns', sa.Column('severity', sa.String(), nullable=True))
    op.add_column('campaigns', sa.Column('intelligence_summary', sa.JSON(), nullable=True))
    op.add_column('sample_campaign_links', sa.Column('signals', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sample_campaign_links', 'signals')
    op.drop_column('campaigns', 'intelligence_summary')
    op.drop_column('campaigns', 'severity')
    # ### end Alembic commands ###
