"""Initial schema

Revision ID: 94b1ac345599
Revises: 
Create Date: 2026-09-09 11:30:46.032931

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '94b1ac345599'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('campaigns',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('risk_score', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('samples',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('filename', sa.String(), nullable=False),
    sa.Column('sha256', sa.String(), nullable=False),
    sa.Column('size', sa.Integer(), nullable=True),
    sa.Column('source', sa.String(), nullable=True),
    sa.Column('submitted_by', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('storage_path', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_samples_sha256'), 'samples', ['sha256'], unique=True)
    op.create_table('analyses',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('sample_id', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('package_name', sa.String(), nullable=True),
    sa.Column('app_name', sa.String(), nullable=True),
    sa.Column('version_name', sa.String(), nullable=True),
    sa.Column('version_code', sa.String(), nullable=True),
    sa.Column('min_sdk', sa.String(), nullable=True),
    sa.Column('target_sdk', sa.String(), nullable=True),
    sa.Column('tlsh', sa.String(), nullable=True),
    sa.Column('certificate_fingerprint', sa.String(), nullable=True),
    sa.Column('risk_score', sa.Integer(), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('threat_narrative', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['sample_id'], ['samples.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('sample_id')
    )
    op.create_index(op.f('ix_analyses_certificate_fingerprint'), 'analyses', ['certificate_fingerprint'], unique=False)
    op.create_index(op.f('ix_analyses_package_name'), 'analyses', ['package_name'], unique=False)
    op.create_index(op.f('ix_analyses_tlsh'), 'analyses', ['tlsh'], unique=False)
    op.create_table('findings',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('sample_id', sa.String(), nullable=True),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('severity', sa.String(), nullable=True),
    sa.Column('category', sa.String(), nullable=True),
    sa.Column('evidence', sa.Text(), nullable=True),
    sa.Column('mitre_technique_id', sa.String(), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['sample_id'], ['samples.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sample_campaign_links',
    sa.Column('sample_id', sa.String(), nullable=False),
    sa.Column('campaign_id', sa.String(), nullable=False),
    sa.Column('relationship', sa.String(), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaigns.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['sample_id'], ['samples.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('sample_id', 'campaign_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('sample_campaign_links')
    op.drop_table('findings')
    op.drop_index(op.f('ix_analyses_tlsh'), table_name='analyses')
    op.drop_index(op.f('ix_analyses_package_name'), table_name='analyses')
    op.drop_index(op.f('ix_analyses_certificate_fingerprint'), table_name='analyses')
    op.drop_table('analyses')
    op.drop_index(op.f('ix_samples_sha256'), table_name='samples')
    op.drop_table('samples')
    op.drop_table('campaigns')
    # ### end Alembic commands ###
