"""Add components and risk factors to Analysis

Revision ID: b85df42b1287
Revises: 94b1ac345599
Create Date: 2026-09-09 22:59:46.086571

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b85df42b1287'
down_revision = '94b1ac345599'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('analyses', sa.Column('activities', sa.JSON(), nullable=True))
    op.add_column('analyses', sa.Column('services', sa.JSON(), nullable=True))
    op.add_column('analyses', sa.Column('receivers', sa.JSON(), nullable=True))
    op.add_column('analyses', sa.Column('risk_factors', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('analyses', 'risk_factors')
    op.drop_column('analyses', 'receivers')
    op.drop_column('analyses', 'services')
    op.drop_column('analyses', 'activities')
    # ### end Alembic commands ###
