"""add dex_data to analysis

Revision ID: ca28bbe9dfd3
Revises: b85df42b1287
Create Date: 2026-09-12 11:12:21.032526

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ca28bbe9dfd3'
down_revision = 'b85df42b1287'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('analyses', sa.Column('dex_data', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('analyses', 'dex_data')
    # ### end Alembic commands ###
